CREATE TABLE IF NOT EXISTS obsidian_vault_grants (
  vault_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  canonical_root TEXT NOT NULL UNIQUE,
  root_identity TEXT NOT NULL,
  write_enabled INTEGER NOT NULL DEFAULT 0 CHECK (write_enabled IN (0, 1)),
  status TEXT NOT NULL DEFAULT 'indexing' CHECK (status IN (
    'no_vault_selected',
    'indexing',
    'healthy',
    'missing',
    'unreadable',
    'permission_denied',
    'root_changed',
    'partial_index',
    'cloud_files_unavailable',
    'watcher_degraded',
    'rebuilding',
    'write_conflict_detected'
  )),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_checked_at TEXT,
  last_scan_started_at TEXT,
  last_scan_completed_at TEXT,
  last_successful_scan_at TEXT,
  index_version INTEGER NOT NULL DEFAULT 1,
  note_count INTEGER NOT NULL DEFAULT 0,
  tag_count INTEGER NOT NULL DEFAULT 0,
  unresolved_link_count INTEGER NOT NULL DEFAULT 0,
  ambiguous_link_count INTEGER NOT NULL DEFAULT 0,
  placeholder_file_count INTEGER NOT NULL DEFAULT 0,
  skipped_file_count INTEGER NOT NULL DEFAULT 0,
  last_error_code TEXT
);
