import { type ComposerEditorHandle } from "./composer/ComposerEditor";
import { type AgentChatGallerySection } from "../../lib/agent-chat-gallery";
import { type AgentPanel } from "./agent-workspace-config";
import type { PendingIssueReport } from "./agent-session-continuity";
import type { QueuedAttachmentFollowUp } from "./composer/follow-up-queue";
import { type AgentWorkspaceError } from "./agent-workspace-errors";
import type { AgentAttachment } from "./agent-workspace-models";
import type { ModelPickerFlyout } from "../settings/ModelPickerPopover";
import type { AgentTaskDto, HermesSessionInfo } from "../../lib/tauri";
import type * as React from "react";

export type UseAgentViewStateDependencies = {
  activityStoreVersion: number;
  agentScrollRef: React.MutableRefObject<HTMLDivElement | null>;
  attachMenuOpen: boolean;
  attachMenuRef: React.MutableRefObject<HTMLDivElement | null>;
  attachTriggerRef: React.MutableRefObject<HTMLButtonElement | null>;
  attachments: AgentAttachment[];
  composerEditorRef: React.MutableRefObject<ComposerEditorHandle | null>;
  composerInSteerStateFor: (input: {
    selectedSessionId?: string;
    provisional: boolean;
    working: boolean;
    submitting: boolean;
    submittingSessionId: string | null;
    demo: boolean;
  }) => boolean;
  composerModelFlyout: ModelPickerFlyout;
  composerModelFromSlash: boolean;
  composerModelOpen: boolean;
  composerModelPopoverRef: React.RefObject<HTMLDivElement>;
  composerModelRootSearchRef: React.RefObject<HTMLInputElement>;
  composerModelSearchRef: React.RefObject<HTMLInputElement>;
  composerModelTriggerRef: React.RefObject<HTMLButtonElement>;
  composerSteerDemo: boolean;
  composerHasContent: boolean;
  errorState: AgentWorkspaceError | null;
  fullModeDraftRef: React.MutableRefObject<boolean>;
  gallerySections: AgentChatGallerySection[] | null;
  hermesSessionItems: HermesSessionInfo[];
  heroGreetingConsumedRef: React.MutableRefObject<boolean>;
  importingFiles: boolean;
  newSessionMode: boolean;
  newSessionModeRef: React.MutableRefObject<boolean>;
  queuedAttachmentFollowUps: Record<string, QueuedAttachmentFollowUp[]>;
  reviewableIssueReports: Record<string, PendingIssueReport>;
  sandboxFirstItemRef: React.MutableRefObject<HTMLButtonElement | null>;
  sandboxMenuOpen: boolean;
  sandboxMenuRef: React.MutableRefObject<HTMLDivElement | null>;
  sandboxMenuWasOpenRef: React.MutableRefObject<boolean>;
  sandboxTriggerRef: React.MutableRefObject<HTMLButtonElement | null>;
  selectedHermesSessionId: string | undefined;
  selectedHermesSessionIdRef: React.MutableRefObject<string | undefined>;
  selectedHermesSessionIsProvisional: boolean;
  selectedTask: AgentTaskDto | undefined;
  setActivePanel: React.Dispatch<React.SetStateAction<AgentPanel>>;
  setAttachMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setConfirmUnrestricted: React.Dispatch<React.SetStateAction<boolean>>;
  setFullModeDraft: React.Dispatch<React.SetStateAction<boolean>>;
  setHeroGreeting: React.Dispatch<React.SetStateAction<string>>;
  setNewSessionMode: React.Dispatch<React.SetStateAction<boolean>>;
  setSandboxMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setSelectedHermesSessionId: React.Dispatch<React.SetStateAction<string | undefined>>;
  setSelectedTaskId: React.Dispatch<React.SetStateAction<string | undefined>>;
  steerCardsBySessionId: Record<string, { id: string; text: string }[]>;
  submitting: boolean;
  submittingHermesSessionId: string | null;
  submittingIssueReportSessionIds: Set<string>;
  upNextDemoFollowUpsBySessionId: Record<string, QueuedAttachmentFollowUp[]>;
  visibleAgentWorkspaceError: (
    error: AgentWorkspaceError | null,
    selectedSessionId: string | undefined,
  ) => AgentWorkspaceError | null;
  modelRootSearch: string;
  setComposerModelFlyout: React.Dispatch<React.SetStateAction<ModelPickerFlyout>>;
  setComposerModelOpen: React.Dispatch<React.SetStateAction<boolean>>;
  setModelRootSearch: React.Dispatch<React.SetStateAction<string>>;
  setModelSearch: React.Dispatch<React.SetStateAction<string>>;
  workingSessionIds: Set<string>;
};
